POST http://localhost:8080/complaints
Content-Type: application/json
Accept: application/json

{
  "productUuid": "45b220e4-c78f-4c9d-8ecf-5bd65b2c168f",
  "reporterEmail": "test@test.com",
  "content": "Treść zgłoszenia 123"
}

###

GET http://localhost:8080/complaints
Accept: application/json

###

GET http://localhost:8080/complaints/1d161ae9-b41a-46dc-bfae-856286d0feea
Accept: application/json

###

PATCH http://localhost:8080/complaints/1d161ae9-b41a-46dc-bfae-856286d0feea
Content-Type: application/json
Accept: application/json

{
  "content": "nowa treść..."
}